name: Package

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  package:
    uses: normlanguage/registry/.github/workflows/package.yml@6acbb8bf194c6ea45661736460184b2d086ebffb
    with:
      norm-version: 0.19.0
